import donell from "@/images/donellj.jpeg";
import donellAlt from "@/images/donell.jpeg";
import kelly from "@/images/kelly.jpg";
import theScript from "@/images/theScript.jpg";
import george from "@/images/george.jpg";
import legend from "@/images/legend.jpg";
import bobby from "@/images/bobby.jpg";
import jaime from "@/images/jaime.png";
import bbd from "@/images/bbd.jpg";
import rk from "@/images/rk.jpeg";

export const STREAMING_PLATFORMS = [
  {
    name: "Spotify",
    icon: "fab fa-spotify",
    color: "hover:bg-green-600",
    url: "https://open.spotify.com/album/5zDcz8n4lq4F7BY6j3TZPe?si=3MuJCZGUSByN9QqpB6qIng",
  },
  {
    name: "Apple Music",
    icon: "fab fa-apple",
    color: "hover:bg-gray-800",
    url: "https://music.apple.com/us/album/d-b-x-the-drakkari-black-xperiment/1869737486",
  },
  {
    name: "SoundCloud",
    icon: "fab fa-soundcloud",
    color: "hover:bg-orange-600",
    url: "https://soundcloud.com/drakkari-black",
  },
  {
    name: "YouTube Music",
    icon: "fab fa-youtube",
    color: "hover:bg-cyan-600",
    url: "https://www.youtube.com/@drakkariblacktv",
  },
];

export const SOCIAL_LINKS = [
  {
    icon: "fab fa-spotify",
    url: "https://open.spotify.com/album/5zDcz8n4lq4F7BY6j3TZPe?si=3MuJCZGUSByN9QqpB6qIng",
  },
  {
    icon: "fab fa-apple",
    url: "https://music.apple.com/us/album/d-b-x-the-drakkari-black-xperiment/1869737486",
  },
  { icon: "fab fa-instagram", url: "https://instagram.com/drakkariblack" },
  { icon: "fab fa-twitter", url: "https://x.com/drakkariblack" },
  { icon: "fab fa-youtube", url: "https://www.youtube.com/@drakkariblacktv" },
];

export const UPCOMING_EVENTS = [
  {
    month: "Aug",
    day: "28",
    year: "2026",
    venue: "Ruby's Elixir",
    location: "St. Pete, FL",
    time: "7:00 PM",
    priceRange: "FREE",
  },
  {
    month: "Sept",
    day: "11",
    year: "2026",
    venue: "Craftails Speakeasy",
    location: "Bradenton, FL",
    time: "8:00 PM",
    priceRange: "FREE",
  },
  {
    month: "Sept",
    day: "25",
    year: "2026",
    venue: "Craftails Speakeasy",
    location: "Bradenton, FL",
    time: "8:00 PM",
    priceRange: "FREE",
  },
];

export const BOOKING_TYPES = [
  "Concert Venues",
  "Music Festivals",
  "Private Events",
  "Corporate Functions",
];

export const SPEAKEASY_SETLIST = [
  // Sorted alphabetically by artist's last name
  {
    artist: "The Beatles",
    title: "My Guitar Gently Weeps",
    album: "",
    genre: "Classic Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Bell Bive Devoe",
    title: "Poison",
    album: "",
    genre: "New Jack Swing",
    spotifyId: "",
    image: bbd,
  },
  {
    artist: "George Benson",
    title: "Gimme The Night",
    album: "",
    genre: "Jazz Fusion",
    spotifyId: "",
    image: george,
  },
  {
    artist: "Jon B",
    title: "Someone To Love",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Justin Bieber",
    title: "Ghost",
    album: "",
    genre: "Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Drakkari Black",
    title: "My Prayer",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Blackstreet",
    title: "Before I Let Go",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Leon Bridges",
    title: "Coming Home",
    album: "",
    genre: "Soul",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Leon Bridges",
    title: "When A Man Cries",
    album: "",
    genre: "Soul",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Bobby Brown",
    title: "Tender Roni",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: bobby,
  },
  {
    artist: "Chris Brown",
    title: "Residuals",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Zach Bryan",
    title: "Something In The Orange",
    album: "",
    genre: "Folk",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Daniel Caesar",
    title: "Get You",
    album: "Freudian",
    genre: "Neo-Soul",
    spotifyId: "1Ov37ksJkYOlX5lJwpvnMW",
    image: "https://i.scdn.co/image/ab67616d0000b273cd945b4e3de57edd28481a3f",
  },
  {
    artist: "Bobby Caldwell",
    title: "What You Won't Do For Love",
    album: "",
    genre: "Soul",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Tevin Campbell",
    title: "Can We Talk",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Kelly Clarkson",
    title: "Since You've Been Gone",
    album: "",
    genre: "Pop Rock",
    spotifyId: "",
    image: kelly,
  },
  {
    artist: "Coldplay",
    title: "Magic",
    album: "",
    genre: "Alternative Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Destin Conrad",
    title: "Same Mistake",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Christopher Cross",
    title: "Sailing",
    album: "",
    genre: "Yacht Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "The Cure",
    title: "Love Song",
    album: "",
    genre: "Alternative Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "P.M. Dawn",
    title: "Die Without You",
    album: "",
    genre: "Hip-Hop Soul",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Goo Goo Dolls",
    title: "Iris",
    album: "",
    genre: "Alternative Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Tears for Fears",
    title: "Mad World",
    album: "",
    genre: "New Wave",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Sam Fischer",
    title: "This City",
    album: "",
    genre: "Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Jaime Foxx",
    title: "Fall For Your Type",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: jaime,
  },
  {
    artist: "The Fray",
    title: "Look After You",
    album: "",
    genre: "Alternative Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Al Green",
    title: "Let's Stay Together",
    album: "",
    genre: "Soul",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Guy",
    title: "I Like",
    album: "",
    genre: "New Jack Swing",
    spotifyId: "4P5KoWXOxwuobLmHXLMobV",
    image: "https://i.scdn.co/image/ab67616d0000b273b6a78c0b15ebfab16b3c85b3",
  },
  {
    artist: "Guy",
    title: "Let's Chill",
    album: "",
    genre: "New Jack Swing",
    spotifyId: "",
    image: "",
  },
  {
    artist: "H.E.R.",
    title: "Hard Place",
    album: "H.E.R.",
    genre: "Contemporary R&B",
    spotifyId: "4ii62XO6w8RPqiJI6iGz6s",
    image: "https://i.scdn.co/image/ab67616d0000b273bb7af5c91e2a1b8d94e3e5d7",
  },
  {
    artist: "Chris Isaak",
    title: "Wicked Game",
    album: "",
    genre: "Alternative Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Michael Jackson",
    title: "Billie Jean",
    album: "",
    genre: "Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Michael Jackson",
    title: "Human Nature",
    album: "",
    genre: "Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Michael Jackson",
    title: "Rock Wit You",
    album: "",
    genre: "Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Jodeci",
    title: "Come And Talk To Me",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Donell Jones",
    title: "You Know What's Up",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: donell,
  },
  {
    artist: "Donell Jones",
    title: "Where I Wanna Be",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: donell,
  },
  {
    artist: "R. Kelly",
    title: "Your Body's Callin Me",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: rk,
  },
  {
    artist: "Kem",
    title: "Love Calls",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Avril Lavigne",
    title: "I'm With You",
    album: "",
    genre: "Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "John Legend",
    title: "All of Me",
    album: "Love in the Future",
    genre: "Soul",
    spotifyId: "3U4isOIWM3VvDubwSI28yq",
    image: "https://i.scdn.co/image/ab67616d0000b273d93ad4c4b8b5b3a2c9f81739",
  },
  {
    artist: "John Legend",
    title: "Tonight",
    album: "",
    genre: "Soul",
    spotifyId: "",
    image: "",
  },
  {
    artist: "John Legend",
    title: "You & I",
    album: "",
    genre: "Soul",
    spotifyId: "",
    image: legend,
  },
  {
    artist: "John Legend",
    title: "Show Me",
    album: "",
    genre: "Soul",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Bruno Mars",
    title: "Locked Out Of Heaven",
    album: "",
    genre: "Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Maxwell",
    title: "Ascension",
    album: "",
    genre: "Neo-Soul",
    spotifyId: "",
    image: "",
  },
  {
    artist: "John Mayer",
    title: "Why Georgia",
    album: "",
    genre: "Pop Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Brian McKnight",
    title: "Anytime",
    album: "",
    genre: "Pop Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Boyz 2 Men",
    title: "Can You Stand The Rain'",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "https://i.scdn.co/image/ab67616d0000b2738863bc11d2aa12b54f5aeb36",
  },
  {
    artist: "George Michael",
    title: "Faith",
    album: "",
    genre: "Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Miguel",
    title: "Sure Thing",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Mint Condition",
    title: "Pretty Brown Eyes",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Ne-Yo",
    title: "Beautiful Monster",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Ne-Yo",
    title: "Closer",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Ne-Yo",
    title: "So Sick",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "New Edition",
    title: "Can You Stand The Rain",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "New Edition",
    title: "If It Isn't Love",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Oasis",
    title: "Wonderwall",
    album: "",
    genre: "Britpop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Passenger",
    title: "Let Her Go",
    album: "",
    genre: "Folk Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Radiohead",
    title: "Creep",
    album: "",
    genre: "Alternative Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Red Hot Chili Peppers",
    title: "Otherside",
    album: "",
    genre: "Alternative Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Prince",
    title: "Kiss",
    album: "",
    genre: "Funk",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Prince",
    title: "Purple Rain",
    album: "",
    genre: "Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Rihanna",
    title: "Stay",
    album: "Unapologetic",
    genre: "Pop",
    spotifyId: "4uLU6hMCjMI75M1A2tKUQC",
    image: "https://i.scdn.co/image/ab67616d0000b273db2d4845bb0b8b3e4d06fc84",
  },
  {
    artist: "Lionel Richie",
    title: "All Night Long",
    album: "",
    genre: "Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Jac Ross",
    title: "So Into You",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Sade",
    title: "Kiss Of Life",
    album: "",
    genre: "Soul",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Jill Scott",
    title: "He Loves Me",
    album: "",
    genre: "Soul",
    spotifyId: "",
    image: "",
  },
  {
    artist: "The Script",
    title: "Break Even",
    album: "",
    genre: "Pop Rock",
    spotifyId: "",
    image: theScript,
  },
  {
    artist: "Seal",
    title: "Kiss From A Rose",
    album: "",
    genre: "Soul",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Shaboozey",
    title: "A Bar Song",
    album: "",
    genre: "Country",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Sam Smith",
    title: "Not The Only One",
    album: "",
    genre: "Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Chris Stapleton",
    title: "Tennessee Whiskey",
    album: "",
    genre: "Country",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Sting",
    title: "Shape Of My Heart",
    album: "",
    genre: "Pop Rock",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Teddy Swims",
    title: "Lose Control",
    album: "",
    genre: "Soul",
    spotifyId: "",
    image: "",
  },
  {
    artist: "SWV",
    title: "Rain",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Tank",
    title: "I Can't Make You Love Me",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Robin Thicke",
    title: "I Need Love",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Justin Timberlake",
    title: "Cry Me A River",
    album: "",
    genre: "Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Tony! Toni! Tone!",
    title: "Anniversary",
    album: "",
    genre: "Pop",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Usher",
    title: "Can You Help Me",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Usher",
    title: "Nice & Slow",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Usher",
    title: "There Goes My Baby",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Luther Vandross",
    title: "Never Too Much",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "The Weeknd",
    title: "I Feel It Coming",
    album: "",
    genre: "R&B",
    spotifyId: "",
    image: "",
  },
  {
    artist: "Stevie Wonder",
    title: "Knocks Me Off My Feet",
    album: "",
    genre: "Soul",
    spotifyId: "",
    image: "",
  },
];
